### ISSUE TITLE
Use TypeScript for code examples in docs

### ISSUE THREAD

**Issue by itsMapleLeaf** [itsMapleLeaf/reacord#25]
Frankly it's a crime that they use JS instead of TS 🙃 

Ideally, it should have that thing that lets you switch between JS or TS, then it'd default to TS

**Comment by polooner** [comment]
I would love to work on this actually!

**Comment by itsMapleLeaf** [comment]
Nice! Feel free to send a PR and I'll take a look when I can 🙂
