### ISSUE TITLE
Usage of .map gets ignored

### ISSUE THREAD

**Issue by 4lve** [itsMapleLeaf/reacord#29]
![image](https://github.com/itsMapleLeaf/reacord/assets/72332750/40dd4d95-4710-450f-a5da-2b97aab4bc2b)
![image](https://github.com/itsMapleLeaf/reacord/assets/72332750/e129edef-b2fd-496b-991f-a8ba4df324d9)

**Comment by itsMapleLeaf** [comment]
Thanks for the issue report! The usage here is incorrect; there's an extra set of parentheses in that code, and it's not returning the JSX. It should be this:

```tsx
return (
	<>
		1
		{new Array(5).fill(0).map((_, row) => <>2</>)}
		3
	</>
)
```

**Comment by 4lve** [comment]
oh, didn't see that, thanks
